; https://docs.platformio.org/en/latest/platforms/espressif32.html

[platformio]
boards_dir = ./boards
extra_configs =
    ; place your global library dependencies here, it will use in all envs
    extra_configs/lib_deps.ini
    ; base envs to extend from, e.g. for different board variants
    extra_configs/base_envs.ini
    ; place extra configuration options here, you can reuse in other envs via ${extra.config_name}
    extra_configs/extra.ini
; uncomment to build an example
; src_dir = ./examples/blink
; src_dir = ./examples/deep-sleep-touch-wakeup
; src_dir = ./examples/esp-now-le

[env]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; or use platformio, versions: https://github.com/platformio/platform-espressif32/releases
; platform = espressif32@6.13.0
; see pioarduino versions: https://github.com/pioarduino/platform-espressif32/releases
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip

; Possible values: "littlefs", "spiffs", "fatfs"
board_build.filesystem = littlefs

build_flags =
    ; to use e.g. as part of the firmware name 
    '-DPIOENV="${PIOENV}"'
 
    ; coding_standards
    ; works only with platformio and not pioarduino
    -Wno-unused-variable
    -Wno-unused-but-set-variable
    -Wunreachable-code

    ; debug level 5=VERBOSE https://docs.platformio.org/en/latest/platforms/espressif32.html#debug-level
    ;  -DCORE_DEBUG_LEVEL=5

    ; config flags, e.g. to enable features in a config.h
    -I lib/config
extra_scripts = pre:extra_script.py
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; uncomment and configure when you have multiple ESPs connected
; upload_port = /dev/tty.usbserial-...
; monitor_port = /dev/tty.usbserial-...


; *********
; * ESP32 *
; *********

; pio board config: https://docs.platformio.org/en/latest/platforms/espressif32.html
[env:esp32dev]
extends = esp32
board = esp32dev

; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/lolin32.html
[env:lolin32]
extends = esp32
board = lolin32

; Wemos https://www.wemos.cc/en/latest/d32/d32_pro.html
; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/lolin_d32_pro.html
[env:lolin_d32_pro]
extends = esp32
board = lolin_d32_pro
build_flags =
    ${esp32.build_flags}
    ${extra.build_flags_psram} ; 4MB PSRAM

[env:ttgo_t_beam_v0_7]
extends = esp32
board = ttgo-t-beam
build_flags =
  ${esp32.build_flags}
  ${extra.build_flags_psram} ; 8MB PSRAM
  -D HAS_BUTTON
  -D HAS_LED
  -D HAS_GPS
  -D USE_SX1276
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = variants

; LILYGO https://www.lilygo.cc/products/t-beam-v1-1-esp32-lora-module
[env:ttgo_t_beam_v1_1]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
extends = esp32
board = esp32dev
platform = ${esp32.platform}
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = variants
build_flags =
  ${esp32.build_flags}
  ${extra.build_flags_psram} ; 8MB PSRAM
  -D HAS_BUTTON
  -D HAS_PMU
  -D HAS_GPS
  -D USE_SX1262

; https://lilygo.cc/products/lora3
; https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/docs/en/t3_v161_sx1276/t3_v161_sx1276_hw.md
; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/ttgo-lora32-v1.html
[env:ttgo_lora32_v1_6_1]
extends = esp32
board = ttgo-lora32-v1
board_build.partitions = huge_app.csv
board_build.variant = ${PIOENV}
board_build.variants_dir = variants
build_flags =
  ${esp32.build_flags}
  -D HAS_DISPLAY_SSD1306
  -D HAS_LED
  -D USE_SX1276
  ; -D HIDE_SPLASH_SCREEN

; ************
; * ESP32-C6 *
; ************
; devkitc-1: https://docs.espressif.com/projects/espressif-esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/index.html
; devkitm-1: https://docs.espressif.com/projects/espressif-esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitm-1/index.html

[env:esp32_c6_n16]
extends = esp32c6
board = esp32-c6-n16

[env:esp32_c6_n4]
extends = esp32c6
board = esp32-c6-n4

; ************
; * ESP32-S2 *
; ************

; TODO http://www.lilygo.cn/prod_view.aspx?TypeId=50033&Id=1321 with psram
; repository: https://github.com/Xinyuan-LilyGO/LilyGo-T-Display-S2
[env:lilygo_t_display_s2]
extends = esp32s2
board = esp32dev ; what about platformio board support and an own board config?

; ************
; * ESP32-S3 *
; ************

; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/esp32s3box.html
[env:esp32s3box]
extends = esp32s3
board = esp32s3box
build_flags =
    ${esp32s3.build_flags}
    -D ESP32S3BOX

; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html
[env:esp32_s3_devkitc_1]
extends = esp32s3
board = esp32-s3-devkitc-1
build_flags =
    ${esp32s3.build_flags}
    -D ESP32_S3_DEVKITC_1
    ; PSRAM is optional
    ; ${extra.build_flags_psram}

; LILYGO: https://www.lilygo.cc/products/t-display-s3
; repository: https://github.com/Xinyuan-LilyGO/T-Display-S3
; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/lilygo-t-display-s3.html
; Buy and support mcuw (affiliate link): https://s.click.aliexpress.com/e/_DE2TNqz
[env:lilygo_t_display_s3]
extends = esp32s3
board = lilygo-t-display-s3
build_flags =
    ${esp32s3.build_flags}
    ${extra.build_flags_psram} ; 8MB PSRAM

; LILYGO: https://www.lilygo.cc/products/t-display-s3-long
; repository: https://github.com/Xinyuan-LilyGO/T-Display-S3-Long
; Buy and support mcuw on aliexpress (affiliate link): https://s.click.aliexpress.com/e/_DEv67TX
[env:lilygo_t_display_s3_long]
extends = esp32s3
board = LilyGo-T-Display-S3-long
board_build.partitions = huge_app.csv

; SeeedStudio: https://www.seeedstudio.com/WT32-3-5-Inch-Display-p-5542.html
; Antratek: https://www.antratek.com/wt32-sco1-plus
; repository: https://github.com/wireless-tag-com/lv_port_esp32
; ESP32-TUX - github: https://github.com/sukesh-ak/ESP32-TUX
[env:wt32_sc01_plus]
extends = env:esp32_s3_devkitc_1
build_flags =
    ${env:esp32_s3_devkitc_1.build_flags}
    ${extra.build_flags_psram} ; 2MB PSRAM

; LILYGO: https://www.lilygo.cc/products/t-watch-s3
; repository: https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/tree/t-watch-s3
; Buy and support mcuw on aliexpress (affiliate link): https://s.click.aliexpress.com/e/_DEZVvH1
[env:lilygo_t_watch_s3]
extends = esp32s3
board = LilyGo-T-Watch-S3
board_build.partitions = huge_app.csv

; LILYGO: https://www.lilygo.cc/products/t-camera-plus-s3
; repository: https://github.com/Xinyuan-LilyGO/T-CameraPlus-S3
; Buy and support mcuw on aliexpress (affiliate link): https://s.click.aliexpress.com/e/_DkytBeT
[env:lilygo_t_cameraplus_s3]
extends = esp32s3
board = LilyGo-T-CameraPlus-ESP32-S3
board_build.partitions = huge_app.csv

; LILYGO: https://www.lilygo.cc/products/t-rgb
; repository: https://github.com/Xinyuan-LilyGO/LilyGo-T-RGB
; Buy and support mcuw on aliexpress (affiliate link): https://s.click.aliexpress.com/e/_Dem6i0b
[env:lilygo_t_rgb]
extends = esp32s3
board = LilyGo-T-RGB
board_build.partitions = huge_app.csv

; LILYGO: https://www.lilygo.cc/products/t-deck
; repository: https://github.com/Xinyuan-LilyGO/T-Deck
; Buy and support mcuw on aliexpress (affiliate link):
;   - LilyGo T-Deck: https://s.click.aliexpress.com/e/_Dem6i0b
;   - LilyGo T-Deck Plus: https://s.click.aliexpress.com/e/_DDeskaP
[env:lilygo_t_deck]
extends = esp32s3
board = LilyGo-T-Deck
board_build.partitions = huge_app.csv

; Waveshare: https://www.waveshare.com/esp32-s3-geek.htm
; demo: https://files.waveshare.com/wiki/ESP32-S3-GEEK/ESP32-S3-GEEK_Code.zip
; pio board config: https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html
[env:esp32_s3_geek]
extends = esp32s3
board = esp32-s3-devkitc-1
build_flags =
    ${esp32s3.build_flags}
    ${extra.build_flags_psram} ; 2MB PSRAM



; ************
; * ESP32-P4 *
; ************

; Generic ESP32-P4 board config with 4MB flash
; board: https://github.com/pioarduino/platform-espressif32/blob/main/boards/esp32-p4.json
[env:esp32_p4]
extends = esp32p4
board = esp32-p4

; Generic ESP32-P4 board config with 16MB flash
; board: https://github.com/pioarduino/platform-espressif32/blob/main/boards/esp32-p4_r3.json
[env:esp32_p4_r3]
extends = esp32p4
board = esp32-p4_r3
board_build.partitions = partitions/partitions_16mb_ota_phy.csv

; ESP32-P4 ESP32-P4 Function EV Board with 16MB flash
; https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32p4/esp32-p4-function-ev-board/index.html
; board: https://github.com/pioarduino/platform-espressif32/blob/main/boards/esp32-p4-evboard.json
[env:esp32_p4_evboard]
extends = esp32p4
board = esp32-p4-evboard
board_build.partitions = partitions/partitions_16mb_ota_phy.csv
