
; Base environments

; ESP32 based modules
[esp32]
  extends = env

; ESP32-C6 based modules
[esp32c6]
  extends = env
  ; Use pioarduino, a community compatible fork of Platformio supporting latest espressif Arduino core
  ; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
  platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
  build_flags =
    ${env.build_flags}
    -D ESP32C6

; ESP32-S2 based modules
[esp32s2]
  extends = env

; ESP32-S3 based modules
[esp32s3]
  extends = env

; ESP32-P4 based modules
[esp32p4]
  extends = env
