; CUSTOM options
; You need manually inject these options into a section
; using ${extra.<name_of_option>} (see below)
[extra]
; https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html
; optional flags only needed for base esp32 boards
; specific boards or boards under the /boards directory are already configured with psram support
build_flags_psram =
  -DBOARD_HAS_PSRAM=1
  -mfix-esp32-psram-cache-issue ; https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html#esp32-rev-v1
